### ISSUE TITLE
Tell what it is

### ISSUE THREAD

**Issue by blakemcbride** [thesofproject/sof-bin#112]
Thanks for the great package!  I've been using it, and it works really well!

Small suggestion

Your README.md file provides a warning and some important specifics.  What I would suggest is that the beginning of that file should describe what the package does.  Having the other stuff afterward is great.

Thanks!

**Comment by marc-hb** [comment]
Thanks @blakemcbride for the feedback! Please feel free to submit a pull request, editing the README.md does not require any advanced knowledge, in fact you are in a better position than most SOF developers because knowing "too much" often means assuming too much.

**Comment by deb-intel** [comment]
@lgirdwood I am happy to read other ReadMe files.  @blakemcbride and all, please feel free to reach out if you find other ReadMe files in need of more intro material.

**Comment by mengdonglin** [comment]
Closing as Readme files are ready and we sync each release with Debian and RedHat
