### ISSUE TITLE
Release 2.4.1

### ISSUE THREAD

**Issue by GreyXor** [thesofproject/sof-bin#115]
Hello,
I wonder where is the bin release of 2.4.1 ? Since 2.2 there's no major upgrade (2.3 and 2.4)
Here : https://github.com/thesofproject/sof/releases/tag/v2.4.1 we can read `Signed binaries for selected Intel platforms are here https://github.com/thesofproject/sof-bin` But I can't find it.
Thank you

**Comment by lgirdwood** [comment]
@GreyXor binaries are here https://github.com/thesofproject/sof-bin/tree/main/v2.4.x/sof-v2.4.1

You are right that 2.3 and 2.4 dont have a sof-bin release page as these are "opt-in" releases intended for developers and integrator and not for most end users. 

We are using "opt-in" atm until v2.5 as there is a significant update in progress with Zephyr RTOS, Windows compatibility and 3rd party processing module support and we don't wont to unintentionally break any end users until the dust has settled on the updates.

**Comment by GreyXor** [comment]
> @GreyXor binaries are here https://github.com/thesofproject/sof-bin/tree/main/v2.4.x/sof-v2.4.1
> 
> You are right that 2.3 and 2.4 dont have a sof-bin release page as these are "opt-in" releases intended for developers and integrator and not for most end users.
> 
> We are using "opt-in" atm until v2.5 as there is a significant update in progress with Zephyr RTOS, Windows compatibility and 3rd party processing module support and we don't wont to unintentionally break any end users until the dust has settled on the updates.

Hello, now that 2.5 is available. can you release sof-bin 2.5 ?

**Comment by marc-hb** [comment]
Do you mean a 2.5 tarball? No, 2.5 is still an opt-in release, see the README in https://github.com/thesofproject/sof-bin/tree/main/v2.5.x

**Comment by GreyXor** [comment]
Thanks, what will be the next opt-out version ?
