### ISSUE TITLE
lots of files/symlinks miss when comparing v2.4.x/sof-v2.4.1 with v2.2.x/sof-v2.2

### ISSUE THREAD

**Issue by tufeigunchu** [thesofproject/sof-bin#117]
I don't think it is right to only copy v2.4.x/sof-v2.4.1 to /lib/firmware/intel/sof

**Comment by marc-hb** [comment]
v2.4.1 is for developers. Please download a complete release from https://github.com/thesofproject/sof-bin/releases This is explained in the README.md
