### ISSUE TITLE
Why not package the dsp-enhancement topologies ?

### ISSUE THREAD

**Issue by smunaut** [thesofproject/sof-bin#130]
There are some interesting topologies in tools/topology/topology1/dsp_enhancement/ that can be used by users but are not included in the release.

**Comment by marc-hb** [comment]
Thanks @smunaut for your feedback. sof-bin is only for production files that are redistributed by Linux distributions. You are supposed to build more experimental stuff from source. This makes sure there's no confusion between the two and that it's not too easy for the vast majority of users to use the wrong file.

cc: @plbossart

Building from source should be as simple as

```shell
git clone sof
cd sof
./scripts/docker-run.sh ./scripts/build-tools.sh
./scripts/docker-run.sh ./scripts/build-tools.sh -h
```
Search https://thesofproject.github.io/latest/index.html for more

**Comment by kv2019i** [comment]
FYI to @singalsu and @lgirdwood

**Comment by lgirdwood** [comment]
Update: @smunaut best to think of this as a staging area, @singalsu is working to bring all modules into default base image in v2.8 with packaged topologies to use them on newer Intel platforms.
