### ISSUE TITLE
Question regarding point releases.

### ISSUE THREAD

**Issue by jbuseman-eng** [thesofproject/sof-bin#160]
How do I use the latest point release firmware?
For example in the 2.7 firmware release there's 2.7.1 and 2.7.2, but the install script does not address these added revisions during install.  There is only a few firmware files in either of these directories, so they're not complete. I'm not sure if manually linking them would work. Advice is appreciated before I go messing something up.

**Comment by marc-hb** [comment]
Did you read https://github.com/thesofproject/sof-bin/blob/main/README.md , especially the part about tarballs?

**Comment by jbuseman-eng** [comment]
I just used the release. I was trying to do it through a github clone, but this was just easier..
