### ISSUE TITLE
Security - Defaults

### ISSUE THREAD

**Issue by MuldersMakes** [thesofproject/sof-bin#170]
default install of coming with distribution debian bookworm, have no owner or group.

root@**# find / -xdev \( -nouser -o -nogroup \) -print
/usr/lib/firmware/intel
/usr/lib/firmware/intel/sof-tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rpl-rt711.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-rt711-rt1308-rt715.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-keyword-detect.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt715-rt711-rt1308-mono.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-dmic2ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5682-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-rt700-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-dmic4ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-dmic4ch-ssp5.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-dmic4ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-mt8195-mt6359-max98390-rt5682-rtnr.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-compr-wm8960-mixer.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-ssp5.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-cs42l42-mx98360a.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rpl-rt711-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-whl-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-dmic2ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98360a-rt5682-rtnr.tplg
/usr/lib/firmware/intel/sof-tplg/sof-mt8195-mt6359-max98390-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-l0-rt1308-l12-rt715-l3.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98390-rt5682-rtnr.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98390-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rpl-rt711-l0-rt1318-l12.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-es8336-ssp1-hdmi-ssp02.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-rt5670.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-es8336-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5651-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt711-rt1308-mono-rt715.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-max98357a-rt5682-pdm1-google-aec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rpl-rt711-l2-rt1316-l01.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rpl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt711-l0-rt1316-l1-mono-rt714-l3.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-pcm512x.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-dmic4ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-sdw-max98373-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-mt8195-mt6359-rt1019-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-max98373-rt5682-igonr.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-rt5640.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-l0-rt1316-l12-rt714-l3.tplg
/usr/lib/firmware/intel/sof-tplg/sof-ehl-rt5660.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-pcm512x-master-44100.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-dmic4ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-dmic2ch-ssp5.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5670-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-idisp-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-mt8195-mt6359-rt1019-rt5682-dts.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-rt298.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-dmic4ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-l2-rt1316-l01-rt714-l3.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-max98373-rt5682-xperi.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-nocodec-ci.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-ehl-rt5660-nohdmi.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-nocodec-ci.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-dmic4ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5640.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-cs42l42.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-dmic4ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-pcm512x-master.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-dmic-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-2ch-kwd.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-wm8960.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-3ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-rt5682-rt1015.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98390-ssp2-rt5682-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-wm8960-kwd.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-rt700.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt1316-l2-mono-rt714-l0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-dmic4ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt1015-nau8825.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-dmic2ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-wm5102-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-max98373-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-l0-rt1316-l13-rt714-l2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt711-rt1308-rt715.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-dmic4ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt1019-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-1ch-pdm1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-da7219.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8mp-compr-wm8960-mixer.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt5682-max98357a.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-dmic2ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5640-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-drc-wm8960.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8mp-drc-wm8960.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98373-nau8825.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-max98357a-rt5682-rtnr.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-dmic4ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-nocodec-sai.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-dmic2ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98390-rt5682-google-aec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-idisp-2ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8mp-wm8960.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-sdw-max98373-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-cx2072x.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-dmic2ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-4ch-kwd.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711.tplg
/usr/lib/firmware/intel/sof-tplg/sof-bdw-rt286.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt700-2ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-max98090.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cnl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-cx2072x-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-cx2072x.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8mp-wm8904.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-1ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5645.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-l0-rt1316-l2-2ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5651.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-da7219-mx98360a.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-cs42888-mixer.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-idisp.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-dmic4ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt1011-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-mt8186-mt6366-rt1019-rt5682s.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5670.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-tdf8532.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98357a-rt5682-2way.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-cs42888.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98357a-rt5682-waves-2way.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-dmic2ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8ulp-9x9-btsco.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-dmic2ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-whl-demux-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rpl-rt1316-l12-rt714-l0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-2ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rpl-rt711-l0-rt1318-l12-rt714-l3.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rn-rt5682-max98360.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt711-rt1316-rt714.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98357a-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-da7219-max98357a.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-dmic4ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-eq-iir-wm8960.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-wm8960-mixer.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-dmic2ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt711-rt1308-mono-rt715.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8ulp-btsco.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-da7213.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rn-rt5682-rt1019.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-dmic4ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8mp-wm8960-kwd.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-dmic2ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98360a-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt1316-l12-rt714-l0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-whl-rt5682-kwd.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-max98357a-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8mp-wm8960-mixer.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-l0-rt1316-l2-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-h-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt1011-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8mp-eq-iir-wm8960.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-da7219-max98390.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-dmic2ch-ssp5.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-ssp5.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98360a-nau8825.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-dmic4ch-ssp5.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-rt5645.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98373-nau8825-dts.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-rt5682-mx98360a.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cnl-rt274.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-dmic4ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-ehl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-cs35l41.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-wm8804.tplg
/usr/lib/firmware/intel/sof-tplg/sof-mt8186-mt6366-da7219-max98357.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic-2ch-pdm1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-bdw-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-dmic2ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-demux-rt5682-max98357a.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt700-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-rt5645-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-nau8824.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98357a-rt5682-waves.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-rt700-2ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98360a-rt5682-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-da7213-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-max98090.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-nocodec-ci.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-rt5651.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-rt5682-kwd.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-dmic2ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-es8336-dmic2ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt1019-nau8825.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt711-rt1308-rt715.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt700.tplg
/usr/lib/firmware/intel/sof-tplg/sof-rpl-rt711-l2-rt1316-l01-rt714-l3.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-dmic4ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-smart-amplifier-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-hda-generic.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-dmic2ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-max98357a-rt5682-pdm1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-acp.tplg
/usr/lib/firmware/intel/sof-tplg/sof-mt8195-mt6359-max98390-rt5682-google-aec-rtnr.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt711-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8-eq-fir-wm8960.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-da7219.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-nocodec.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-l0-rt1316-l3-2ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt1316-l2-mono-rt714-l3.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98357a-rt5682-rtnr.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-demux-rt5682.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt711-rt1308-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-dmic2ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-es8336-dmic2ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-nau8825.tplg
/usr/lib/firmware/intel/sof-tplg/sof-icl-es8336-dmic2ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-imx8mp-eq-fir-wm8960.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-rt5682-kwd.tplg
/usr/lib/firmware/intel/sof-tplg/sof-bdw-rt5640.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-da7219.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-es8316-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-da7213.tplg
/usr/lib/firmware/intel/sof-tplg/sof-jsl-rt5682-rt1015-xperi.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt711-rt1308-2ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-dmic4ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt5682-ssp0-max98373-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-bdw-rt5677.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98360a-rt5682-2way.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-dmic2ch-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-es8336-ssp1.tplg
/usr/lib/firmware/intel/sof-tplg/sof-byt-es8316.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cml-es8336-dmic4ch-ssp2.tplg
/usr/lib/firmware/intel/sof-tplg/sof-glk-da7219-kwd.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-rt711-l2-rt1316-l01.tplg
/usr/lib/firmware/intel/sof-tplg/sof-apl-demux-pcm512x.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98357a-rt5682-4ch.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-es8336-dmic4ch-ssp0.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-max98357a-rt5682-pdm1-drceq.tplg
/usr/lib/firmware/intel/sof-tplg/sof-tgl-rt5682-ssp0-max98373-ssp2-xperi.tplg
/usr/lib/firmware/intel/sof-tplg/sof-cht-es8316.tplg
/usr/lib/firmware/intel/sof-tplg/sof-adl-max98360a-rt5682-waves.tplg
/usr/lib/firmware/intel/sof
/usr/lib/firmware/intel/sof/sof-tgl.ldc
/usr/lib/firmware/intel/sof/sof-adl-s.ri
/usr/lib/firmware/intel/sof/sof-adl-n.ldc
/usr/lib/firmware/intel/sof/sof-bdw.ldc
/usr/lib/firmware/intel/sof/sof-cht.ldc
/usr/lib/firmware/intel/sof/sof-rpl-s.ldc
/usr/lib/firmware/intel/sof/sof-ehl.ri
/usr/lib/firmware/intel/sof/intel-signed
/usr/lib/firmware/intel/sof/intel-signed/sof-adl-s.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-ehl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-adl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-apl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-rpl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-icl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-jsl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-cnl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-adl-n.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-rpl-s.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-tgl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-glk.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-cfl.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-tgl-h.ri
/usr/lib/firmware/intel/sof/intel-signed/sof-cml.ri
/usr/lib/firmware/intel/sof/sof-apl.ldc
/usr/lib/firmware/intel/sof/sof-adl.ri
/usr/lib/firmware/intel/sof/sof-apl.ri
/usr/lib/firmware/intel/sof/sof-rpl.ri
/usr/lib/firmware/intel/sof/sof-glk.ldc
/usr/lib/firmware/intel/sof/sof-cnl.ldc
/usr/lib/firmware/intel/sof/sof-byt.ldc
/usr/lib/firmware/intel/sof/community
/usr/lib/firmware/intel/sof/community/sof-adl-s.ri
/usr/lib/firmware/intel/sof/community/sof-ehl.ri
/usr/lib/firmware/intel/sof/community/sof-adl.ri
/usr/lib/firmware/intel/sof/community/sof-apl.ri
/usr/lib/firmware/intel/sof/community/sof-rpl.ri
/usr/lib/firmware/intel/sof/community/sof-icl.ri
/usr/lib/firmware/intel/sof/community/sof-jsl.ri
/usr/lib/firmware/intel/sof/community/sof-cnl.ri
/usr/lib/firmware/intel/sof/community/sof-adl-n.ri
/usr/lib/firmware/intel/sof/community/sof-rpl-s.ri
/usr/lib/firmware/intel/sof/community/sof-tgl.ri
/usr/lib/firmware/intel/sof/community/sof-glk.ri
/usr/lib/firmware/intel/sof/community/sof-cfl.ri
/usr/lib/firmware/intel/sof/community/sof-tgl-h.ri
/usr/lib/firmware/intel/sof/community/sof-cml.ri
/usr/lib/firmware/intel/sof/sof-byt.ri
/usr/lib/firmware/intel/sof/sof-rpl.ldc
/usr/lib/firmware/intel/sof/sof-icl.ri
/usr/lib/firmware/intel/sof/sof-jsl.ri
/usr/lib/firmware/intel/sof/sof-cnl.ri
/usr/lib/firmware/intel/sof/sof-adl.ldc
/usr/lib/firmware/intel/sof/sof-adl-n.ri
/usr/lib/firmware/intel/sof/sof-cml.ldc
/usr/lib/firmware/intel/sof/sof-rpl-s.ri
/usr/lib/firmware/intel/sof/sof-adl-s.ldc
/usr/lib/firmware/intel/sof/sof-icl.ldc
/usr/lib/firmware/intel/sof/sof-cfl.ldc
/usr/lib/firmware/intel/sof/sof-tgl.ri
/usr/lib/firmware/intel/sof/sof-ehl.ldc
/usr/lib/firmware/intel/sof/sof-tgl-h.ldc
/usr/lib/firmware/intel/sof/sof-glk.ri
/usr/lib/firmware/intel/sof/sof-cfl.ri
/usr/lib/firmware/intel/sof/sof-cht.ri
/usr/lib/firmware/intel/sof/sof-bdw.ri
/usr/lib/firmware/intel/sof/sof-jsl.ldc
/usr/lib/firmware/intel/sof/sof-tgl-h.ri
/usr/lib/firmware/intel/sof/sof-cml.ri

**Comment by marc-hb** [comment]
> find / -xdev ( -nouser -o -nogroup )
> [...]
> have no owner or group.

That's not what `-nouser` means, check `man find`.

This is a problem with Debian packaging, please report this issue to Debian. @mrhpearson are you still packaging SOF for Debian?

The user and permissions in sof-bin.tgz file are random and should be discarded when packaging.

**Comment by mrhpearson** [comment]
Thanks for flagging this - yes I am still the packager.

I'm working on an update to the latest release but am a bit behind - I had it ready but found issues with the Meteorlake platforms not working and hadn't quite figured what had changed to break things...

I'll look at fixing this with the next update.

@MuldersMakes - I guess the correct way of doing this is a Debian bug for the issue? Or you can just wait for me to fix it ;) Up to you.

Mark

**Comment by marc-hb** [comment]
> I had it ready but found issues with the Meteorlake platforms not working and hadn't quite figured what had changed to break things...

Maybe https://github.com/thesofproject/sof/issues/9243? I don't know whether that bug was ever in a release...

**Comment by mrhpearson** [comment]
> > I had it ready but found issues with the Meteorlake platforms not working and hadn't quite figured what had changed to break things...
> 
> Maybe [thesofproject/sof#9243](https://github.com/thesofproject/sof/issues/9243)? I don't know whether that bug was ever in a release...

Nah - it was a packaging problem on my side. I need to go and refresh my memory but I think the MTL files moved and whatever I'm doing in the packaging somehow missed it or didn't account for it. This summer has been too hectic.

I see there's a new release out so I am going to target getting that done.

Mark
