### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by dragossusi** [thesofproject/sof-bin#52]
I tried this project but doesn't work on latest Intel processors.
How do I remove this?

**Comment by marc-hb** [comment]
Which processor and what failure do you have?

The "installer" merely copies files, into 3 directories:
https://github.com/thesofproject/sof-bin/blob/main/README.md
So you can delete these directories are restore your backup.

If you forgot to make a backup, you can re-install the linux-firmware package from your distribution.

**Comment by dragossusi** [comment]
I didn't backup anything.

**Comment by lgirdwood** [comment]
> I tried this project but doesn't work on latest Intel processors.
> How do I remove this?

Which processor ? It works on processors from Baytrail to Tigerlake (latest).

**Comment by marc-hb** [comment]
@dragossusi ok to close?

**Comment by dragossusi** [comment]
yes, the problem we had was with audio and microphone, they didnt work on a dell Workstation Dell Precision 5750 17" FHD+ i7-10750H

**Comment by marc-hb** [comment]
> i7-10750H

Seems to be CML
