### ISSUE TITLE
1.9 is missing under "Releases" page

### ISSUE THREAD

**Issue by joakim-tjernlund** [thesofproject/sof-bin#57]
Can you add there?

**Comment by marc-hb** [comment]
Sorry I was waiting for https://github.com/thesofproject/sof/pull/4804 resolution and then I got busy with other things.

Should be good as soon as #58 is merged

**Comment by joakim-tjernlund** [comment]
Seem #58 is merged now :)

**Comment by marc-hb** [comment]
Done

**Comment by joakim-tjernlund** [comment]
No release notes?

**Comment by marc-hb** [comment]
To keep things simple I just added a link from https://github.com/thesofproject/sof-bin/releases/tag/v1.9 to https://github.com/thesofproject/sof/releases/tag/v1.9. I think the "inconvenience" of one extra click is acceptable and better than copy/paste/diverge. I'll update the HOWTO.
