### ISSUE TITLE
(ALSA) Intel driver not working

### ISSUE THREAD

**Issue by GFoniX** [thesofproject/sof-bin#67]
Hello,
I don't know if it's the right place for this.
My internal output and input devices is not recognised.
Alsa only found headphone jack output.

On this link there is all the devices on my computer [https://linux-hardware.org/?probe=66cbadb1c1](url)

Hope it can be fix

(I have Tiger Lake-LP Smart Sound Technology Audio Controller)

**Comment by marc-hb** [comment]
> I don't know if it's the right place for this.

Sorry it's not. Moreover there is not enough information to help you - in any bug tracker.

You must follow all the steps here first: https://help.ubuntu.com/community/SoundTroubleshootingProcedure
