### ISSUE TITLE
SOF bin

### ISSUE THREAD

**Issue by channelup69** [thesofproject/sof-bin#78]
I'm currently running Chrome OS with the brunch framework. Is it possible to install this on Chrome OS?

Thanks

**Comment by marc-hb** [comment]
Dunno what brunch is sorry.

This might help: https://github.com/thesofproject/sof/issues/5361

**Comment by channelup69** [comment]
Thank you sir I will read about it.

Brunch Frame Work in case your wondering.

https://github.com/sebanc/brunch

**Comment by cujomalainey** [comment]
Hi I'm the ChromeOS DSP lead and yes many of our devices run SOF and are designed to let developers build their own firmware with ease as we use the public keys on modern devices. Let me know if you have any questions.
