### ISSUE TITLE
go.sh in 1.5 has "nothing implemented"

### ISSUE THREAD

**Issue by EvanCarroll** [thesofproject/sof-bin#8]
I'm sure this isn't an oversight, but we should probably have a ticket. Someone will open anyway. The instructions say to use `go.sh` and there is nothing inside of it.

**Comment by lgirdwood** [comment]
@EvanCarroll I think it was on @xiulipan TODO list, but it seems you were first with some code :)

**Comment by marc-hb** [comment]
We don't use go.sh nor branches any more, @EvanCarroll OK to close this?

**Comment by EvanCarroll** [comment]
yes.
