### ISSUE TITLE
v2.2 has incorrect symlinks and v2.2.1 not released yet

### ISSUE THREAD

**Issue by mrhpearson** [thesofproject/sof-bin#87]
Raising this issue for tracking as emails are being ignored. Hoping someone on the SOF team can help get this moving.

PR #84 to fix the incorrect symlinks in 2.2 was accepted a month ago but (as previously agreed) a 2.2.1 release is needed to get this update and hasn't been done.

Please can we get an updated and working release? I've been holding off on doing the udpated package for Debian until it's available.

Thanks!
Mark

**Comment by lgirdwood** [comment]
@mengdonglin are we good to go ? @mrhpearson IIUC, we had some topology updates pending validation that also had to go in this tag. @plbossart fyi.

**Comment by keqiaozhang** [comment]
> @mengdonglin are we good to go ?

The topology updates passed the validation, we are good to go now, I will prepare the v2.2.1 sof-bin release.

**Comment by mengdonglin** [comment]
@lgirdwood What version would you recommend for this release? v2.2.1 or v2.2a?  All updates are only for topology, not for FW.

**Comment by keqiaozhang** [comment]
PR is submitted: https://github.com/thesofproject/sof-bin/pull/88

**Comment by lgirdwood** [comment]
> PR is submitted: #88

Merged. @keqiaozhang  can you add some release notes now to sof-bin GH. We need to state this is topology only fixes. Thanks

**Comment by mrhpearson** [comment]
Thanks for the update. I didn't realise you were planning more changes. I thought the 2.2.1 release was going to be just 2.2 but with the symlinks corrected.

It's minor, and just my opinion - but if you're doing more changes in this then suggest you go to v2.3 (and get the symlinks right). It will mean I don't have to mess with my build scripts for the debian packager and I suspect other distro's are the same. Keeping numbering consistent seems to make more sense to me.

**Comment by mengdonglin** [comment]
> Thanks for the update. I didn't realise you were planning more changes. I thought the 2.2.1 release was going to be just 2.2 but with the symlinks corrected.
> 
> It's minor, and just my opinion - but if you're doing more changes in this then suggest you go to v2.3 (and get the symlinks right). It will mean I don't have to mess with my build scripts for the debian packager and I suspect other distro's are the same. Keeping numbering consistent seems to make more sense to me.

@mrhpearson Sorry we didn't realized you only need the symlinks right and make you have to update your build scripts. We planned v2.2.1 with these topology updates 2 weeks ago. 

Now the minor version only changes for a new quarterly release. e.g. v2.2 is Q2 release and v2.3 will be Q3 release.  stable-v2.2 branch may be maintained for most mature platforms for long time and we're adding new topologies to this branch without change for FW. @lgirdwood will have more discussion and alignment with the community.

**Comment by lgirdwood** [comment]
@mrhpearson fwiw, separation of FW from topology repos/releases is a topic for TSC. 
I would also be happy to take any debian script/config used for packaging upstream if needed if that helps you ? Would be delighted if you had time to be a reviewer on sof-bin repo too since you are Debian packager ?

**Comment by mrhpearson** [comment]
Happy to be a reviewer - would love to get a notification when there is a new release (I check in occaisionally but I know I missed a few releases)

If interested - the repo I do the packaging from is: https://salsa.debian.org/mpearson/firmware-sof
I do the updates and testing then get help for delivering it to Debian as I'm not a Debian Maintainer (yet)

Thanks for the details on the update - I wondered why it was taking time for something I thought was minor. The problem I had is that the v2.2 release was just plain wrong - so I didn't package it to avoid propagating the mistake.
I can release 2.2.1 but I'm actually wondering if 2.3 is not too far away them maybe I should wait for that? Do you have an estimate date? I've not had anybody from the community asking for an update yet - I'm just trying to be a good maintainer :)

Mark

**Comment by marc-hb** [comment]
> @lgirdwood What version would you recommend for this release? v2.2.1 or v2.2a? All updates are only for topology, not for FW.

Similar, older discussion:
- #76

**Comment by mrhpearson** [comment]
Looks like you've been through this before :)
I'm not sure how my packaging script will cope with the 'a' - I'll check it out and see. I think it should work...

Just curious - why the hard requirement on minor versions only updating quarterly? From my limited perspective - new release (for whatever reasons) then just bump the minor version number and keep life simple.

**Comment by mrhpearson** [comment]
Update v2.2.1 looks good. I have an updated package and am just cycling through testing it on the various Intel generations and will look at it getting released to the Debian repo's.
Thanks for getting this fixed. Closing ticket.

**Comment by marc-hb** [comment]
I submitted a checklist update about this, please help review: #89

**Comment by mrhpearson** [comment]
Looks good to me - thanks!
